version: 2

build:
  os: ubuntu-22.04
  tools:
    python: 3
  apt_packages:
    - cmake
    - g++
    - make
    - pybind11-dev
    - python3-dev
    - python3-numpy
    - python3-requests
    
  jobs:
    pre_build:
      - pwd
      - whoami
      - sudo whoami

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  builder: html
  configuration: docs/conf.py

