version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-4.10"
  jobs:
    pre_build:
      - python ./.ci/readthedocs/build.py
      - cd docs && mkdir _build && doxygen && cd ..

conda:
  environment: .ci/readthedocs/conda.yml

sphinx:
  builder: html
  configuration: docs/conf.py

