#!/bin/sh

set -ev

PREFIX=/Library/Frameworks/Python.framework/Versions

for PYBIN in ${PREFIX}/2.7/bin ${PREFIX}/3.[6-9]*/bin; do
    echo "Building wheel with" ${PYBIN}
  
    PYTHON=$(ls ${PYBIN}/python?.?)
    PIP="${PYTHON} -m pip"
    
    ${PYTHON} setup.py -q bdist
    
    export PYTHONPATH=$(${PYTHON} -c 'import sysconfig; import sys; print("build/lib.{}-{}.{}".format(sysconfig.get_platform(), *sys.version_info[:2]))')
    ${PIP} install $(${PYTHON} -c 'import sys; print("numpy" if sys.version >= "3.5" else "numpy<=1.16.4")')
    ${PYTHON} -m unittest discover -s tests/python/
    unset PYTHONPATH
    
    ${PIP} install wheel
    ${PYTHON} setup.py -q bdist_wheel
done
