#!/bin/sh

set -ev

export WORKSPACE=${WORKSPACE:?}

cd ${WORKSPACE}
export SYCOMORE_TEST_DATA=${WORKSPACE}/tests/data

eval "$(pyenv init -)"

for PYTHON_VERSION in $(pyenv versions --bare); do
    echo "Building wheel with" ${PYTHON_VERSION}
    
    pyenv shell ${PYTHON_VERSION}
    
    python setup.py -q bdist
    
    export PYTHONPATH=$(python -c 'import sysconfig; import sys; print("build/lib.{}-{}.{}".format(sysconfig.get_platform(), *sys.version_info[:2]))')
    python -m unittest discover -s tests/python/
    unset PYTHONPATH
    
    python setup.py -q bdist_wheel
done
