#!/bin/sh

set -ev

for PACKAGE in openssl pybind11 pyenv readline sqlite3 xz zlib; do
    VERSIONS=$(brew ls --versions ${PACKAGE} || true)
    if [ -z "${VERSIONS}" ]; then
        COMMAND="install"
    else
        OUTDATED=$(brew outdated ${PACKAGE} || true)
        if [ -z "${OUTDATED}" ]; then
            COMMAND=""
        else
            COMMAND="upgrade"
        fi
    fi
    
    if [ -n "${COMMAND}" ]; then
        brew ${COMMAND} ${PACKAGE}
    fi
done

pyenv install -s 3.4.10
pyenv install -s 3.5.7
pyenv install -s 3.6.9
pyenv install -s 3.7.4

eval "$(pyenv init -)"
for PYTHON_VERSION in $(pyenv versions --bare); do
    pyenv shell ${PYTHON_VERSION}

    NUMPY=$(python -c 'import sys; print("numpy" if sys.version >= "3.5" else "numpy<=1.16.4")')
    pip install -U ${NUMPY} setuptools wheel
done
