#!/bin/sh

set -ev

export PYTHON=${PYTHON:-python}

for PACKAGE in boost cmake libomp pybind11; do
    VERSIONS=$(brew ls --versions ${PACKAGE} || true)
    if [ -z "${VERSIONS}" ]; then
        COMMAND="install"
    else
        OUTDATED=$(brew outdated ${PACKAGE} || true)
        if [ -z "${OUTDATED}" ]; then
            COMMAND=""
        else
            COMMAND="upgrade"
        fi
    fi
    
    if [ -n "${COMMAND}" ]; then
        brew ${COMMAND} ${PACKAGE}
    fi
done

NUMPY=$(${PYTHON} -c 'import sys; print("numpy" if sys.version >= "3.5" else "numpy<=1.16.4")')
${PYTHON} -m pip install -U ${NUMPY}
