#!/bin/sh

set -ev

export WORKSPACE=${WORKSPACE:?}

cd ${WORKSPACE}

mkdir -p build
mkdir -p install
cd build
cmake \
  -D CMAKE_INSTALL_PREFIX="${WORKSPACE}/install" \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_CXX_FLAGS="-march=native -fno-math-errno -funsafe-math-optimizations -fno-rounding-math -fno-signaling-nans -fcx-limited-range -fexcess-precision=fast -D__FAST_MATH__"
  ${CMAKE_OPTIONS} \
  ..
make ${MAKE_OPTIONS} install
