#!/bin/sh

set -ev

apt-get update

UNOFFICIAL=https://iris-packages.s3.unistra.fr

apt-get -y --no-install-recommends install gnupg software-properties-common wget
wget -O - https://iris-packages.s3.unistra.fr/gpg.key | apt-key add -
DIST=$(lsb_release -cs)
if [ "${DIST}" = "stretch"]; then
  apt-get -y --no-install-recommends install apt-transport-https
fi
if wget -q -O /dev/null ${UNOFFICIAL}/apt/dists/${DIST}/Release; then
  add-apt-repository "deb ${UNOFFICIAL}/apt ${DIST} main"
fi
apt-get update

apt-get -y --no-install-recommends install \
    cmake g++ libboost-dev make ninja-build \
    pybind11-dev python3-pybind11 python3-dev \
    libboost-test-dev python3-numpy

cd ~/
wget -q -O /dev/stdout https://github.com/xtensor-stack/xsimd/archive/7.5.0.tar.gz | tar -x -z -f -
cd xsimd-7.5.0
cmake -DCMAKE_INSTALL_PREFIX=~/local .
cmake --build . --target install
cd ${WORKSPACE}
