#!/bin/sh

set -ev

apt-get update

BINTRAY=http://dl.bintray.com/lamyj/generic/apt

apt-get -y --no-install-recommends install gnupg software-properties-common wget
wget -O - http://dl.bintray.com/lamyj/generic/gpg.key | apt-key add -
if wget -q -O /dev/null ${BINTRAY}/dists/$(lsb_release -cs)/Release; then
  add-apt-repository "deb ${BINTRAY} $(lsb_release -cs) main"
fi
apt-get update

apt-get -y --no-install-recommends install \
    cmake g++ libboost-dev make \
    pybind11-dev python3-pybind11 python3-dev \
    libboost-test-dev python3-numpy
